"""add_img_to_place

Revision ID: 10f409bbc8a3
Revises: e223adebe078
Create Date: 2025-12-24 01:06:38.930536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f409bbc8a3'
down_revision: Union[str, Sequence[str], None] = 'e223adebe078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'image_url')
    # ### end Alembic commands ###
