"""coordinates

Revision ID: a710960ab90b
Revises: 5c0efdd7eab9
Create Date: 2025-12-24 13:34:46.117205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a710960ab90b'
down_revision: Union[str, Sequence[str], None] = '5c0efdd7eab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'lon')
    op.drop_column('places', 'lat')
    # ### end Alembic commands ###
