"""add_lat_lon_to_places

Revision ID: e223adebe078
Revises: 2ddd0dfea1c0
Create Date: 2025-12-24 01:03:12.559202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e223adebe078'
down_revision: Union[str, Sequence[str], None] = '2ddd0dfea1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'lon')
    op.drop_column('places', 'lat')
    # ### end Alembic commands ###
